swagger: "2.0"

info:
  version: 1.0.0
  title: Simple API
  description: A simple API to learn how to write OpenAPI Specification

schemes:
  - http
host: localhost:8080
basePath: /api

paths:
  /datagrid:
    get:
      summary: Gets a paginated list of data-grid entries.
      responses:
        200:
          description: List of items
          schema:
            type: array
            items:
              properties:
                category:
                  type: string
                name:
                  type: string
                price:
                  type: number
                stocked:
                  type: string
